version: "3.9"  # optional since v1.27.0
services:
  # influxdb:
  #   image:  influxdb:1.8.9
  #   container_name: influxdb
  #   volumes:
  #     - ./influxdb:/var/lib/influxdb:rw
  #     - ./influxdb_config:/etc/influxdb:rw
  #   ports:
  #     - "8086:8086/tcp"
  # influxdb_cli:
  #   links:
  #     - influxdb
  #   image: influxdb:1.8.9
  #   container_name: influxdb_cli
  #   volumes:
  #     - ./influxdb:/var/lib/influxdb:rw
  #     - ./influxdb_config:/etc/influxdb/:rw
  #   entrypoint: ["./entrypoint.sh"]
  #   restart: on-failure:10
  #   depends_on:
  #     - influxdb
  telegraf:
    image:  telegraf
    container_name: telegraf
    restart: always
    links:
      # - influxdb
      - questdb
    volumes:
      - ./telegraf/.:/etc/telegraf/.:rw
    ports:
      - "8125:8125/udp"
      - "8092:8092/udp"
      - "8094:8094/tcp"
    # depends_on:
    #   - influxdb_cli
  grafana:
    image:  grafana/grafana
    container_name: grafana
    volumes:
    - ./GF_PATHS_CONFIG/:/etc/grafana/.:rw
    - ./GF_PATHS_DATA/:/var/lib/grafana/.:rw
    - ./GF_PATHS_HOME/:/usr/share/grafana/.:rw
    - ./GF_PATHS_LOGS/:/var/log/grafana/.:rw
    - ./GF_PATHS_PLUGINS/:/var/lib/grafana/plguins/.:rw
    - ./GF_provisioning/:/etc/grafana/provisioning/datasources/.:rw
    links:
      # - influxdb
      - questdb
    ports:
      - "3000:3000/tcp"
    # depends_on:
    #   - influxdb
  # kapacitor:
  #   image:  kapacitor
  #   container_name: kapacitor
  #   # volumes:
  #   # - ./kapacitor/:/etc/kapacitor/.:rw
  #   environment:
  #     KAPACITOR_HOSTNAME: kapacitor
  #     KAPACITOR_INFLUXDB_0_URLS_0: http://influxdb:8086
  #   links:
  #   - influxdb
  #   ports:
  #   - "9092:9092/tcp"
  # chronograf:
  #   image:  chronograf
  #   container_name: chronograf
  #   volumes:
  #   - ./chronograf/:/etc/default/.:rw
  #   environment:
  #     INFLUXDB_URL: http://influxdb:8086
  #     KAPACITOR_URL: http://kapacitor:9092
  #   ports:
  #   - "8888:8888/tcp"
  #   links:
  #   - influxdb
  #   - kapacitor
  # nodered:
  #   image: nodered/node-red
  #   container_name: nodered
  #   volumes:
  #   - ./nodered/:/data/.:rw
  #   ports:
  #   - "1880:1880/tcp"
  # mqtt:
  #   image: eclipse-mosquitto
  #   container_name: mqtt
  #   volumes:
  #   - ./mqtt/mosquitto.conf:/mosquitto/config/mosquitto.conf:rw
  #   ports:
  #   - "1883:1883"
  #   - "9001:9001"
  questdb:
    image: questdb/questdb
    container_name: questdb
    volumes:
    - ./questdb/:/root/.questdb/
    ports:
    - "9000:9000/tcp"
    - "9009:9009/tcp"
    - "8812:8812/tcp"
    - "9003:9003/tcp"

# networks:
#   bridge:
# volumes:
#   telegraf-volume:
#     external: true
#   influxdb-volume:
#     external: true
#   influxdb_cli-volume:
#     external: true
